// Core surface barrel aggregating foundational modules re-exported from allTS.ts.
export * from "./endo-2category"
export * from "./comonad-k1"
export * from "./array-recursion"
export * from "./task"
export * from "./validation"
export * from "./reader-task-option"
export * from "./json-canonical"
export * from "./decoder"
export * from "./core"
export * from "./typeclasses"
export * from "./catTransforms"
export * from "./reader-tools"
export * from "./json-recursion"
